21.01.2023

In [2]:
import numpy as np # Numpy kütüphanesini içe aktarma

In [4]:
# Versiyon sorgulama
np.__version__

'1.21.1'

In [5]:
# Örnek bir dizi oluşturma 
dizi = np.array([1,2,3,4]) 
print(dizi)
print(type(dizi))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# Tuple ile numpy dizini oluşturma
demet = np.array((1,2,3,4,5))
print(demet)
print(type(demet))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# 0B, boyutu olmayan scalar numpy dizisi oluşturmak
B0 = np.array(45)
print(B0, "\n")
print("eksen boyutu: ", B0.ndim) # Boyut sorgulama

45 

eksen boyutu:  0


In [8]:
# 1B tek boyutlu(eksenli) vektör oluşturmak
B1 = np.array([45,50,60])
print(B1, "\n")
print("eksen boyutu: ", B1.ndim) # Boyut sorgulama

[45 50 60] 

eksen boyutu:  1


In [9]:
# 2B iki boyutlu(eksenli) tensör oluşturmak
B2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(B2, "\n")
print("eksen boyutu: ", B2.ndim) # Boyut sorgulama

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

eksen boyutu:  2


In [10]:
# 3B üç boyutlu(eksenli) tensör oluşturmak
B3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(B3, "\n")
print("eksen boyutu: ", B3.ndim) # Boyut sorgulama

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

eksen boyutu:  3


In [11]:
# Dizi boyutu belirleyerek oluşturmak 
dizi = np.array([1,2,3,4], ndmin = 5)
print(dizi, "\n")
print("eksen boyutu: ", dizi.ndim)

[[[[[1 2 3 4]]]]] 

eksen boyutu:  5


In [12]:
# 1B Dizilere erişim
B1 = np.array([45,50,60])
print(B1, "\n")
print("erişilen indeks: ", B1[0])

[45 50 60] 

erişilen indeks:  45


In [13]:
B1 = np.array([45,50,60])
print(B1, "\n")
print("erişilen indeks: ", B1[2])

[45 50 60] 

erişilen indeks:  60


In [14]:
B1 = np.array([45,50,60])
print(B1, "\n")
print("indeks toplamları: ", B1[0] + B1[2])

[45 50 60] 

indeks toplamları:  105


In [15]:
# 2B dizilere erişim
B2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(B2, "\n")
print("2.eleman 1.satıra erişim: ", B2[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

2.eleman 1.satıra erişim:  2


In [16]:
# 2B dizilere erişim
B2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(B2, "\n")
print("5.eleman 2.satıra erişim: ", B2[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

5.eleman 2.satıra erişim:  10


In [17]:
B2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(B2, "\n")
print("1.satır 3.elemanı ile 2.satır 1.elemanı ile toplamları: ", B2[0,2] + B2[1,0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

1.satır 3.elemanı ile 2.satır 1.elemanı ile toplamları:  9


In [18]:
# 3B üç boyutlu(eksenli) diziye erişim
B3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(B3, "\n")
print("1.satır elemanlarına erişim: ", B3[0,0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

1.satır elemanlarına erişim:  [1 2 3]


In [19]:
B3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(B3, "\n")
print("2.satır elemanlarına erişim: ", B3[0,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

2.satır elemanlarına erişim:  [4 5 6]


In [20]:
B3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(B3, "\n")
print("1.satır elemanlarına erişim: ", B3[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

1.satır elemanlarına erişim:  [[1 2 3]
 [4 5 6]]


In [21]:
# Negatif indeksleme
B2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(B2, "\n")
print("erişilen indeks: ", B2[0,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

erişilen indeks:  5


In [22]:
# Negatif indeksleme
B1 = np.array([[1,2,3,4,5]])
print(B1, "\n")
print("erişilen indeks: ", B1[0,-2])

[[1 2 3 4 5]] 

erişilen indeks:  4
