21.01.2023

In [ ]:
import numpy as np

In [ ]:
# Aşağıdaki diziden dizin 1'den dizin 5'e öğeleri dilimleyin:
B1 = np.array([1,2,3,4,5,6,7])
dilimleme = B1[1:5]
print(dilimleme)

[2 3 4 5]


In [ ]:
# Öğeleri dizin 4'ten dizinin sonuna kadar dilimleyin:
dilimleme = B1[4:]
print(dilimleme)

[5 6 7]


In [ ]:
# Öğeleri başlangıçtan dizin 4'e kadar dilimleyin (dahil değildir):
dilimleme = B1[:4]
print(dilimleme)

[1 2 3 4]


In [ ]:
# Negatif dilimleme
# Dizin 3'ten sondan dizin 1'e kadar sondan dilimleyin:
B1 = [1,2,3,4,5,6,7]
negatifDilim = B1[-3:-1]
print(negatifDilim)

[5, 6]


In [ ]:
# Dizin 1'den dizin 5'e diğer tüm öğeleri döndürün:
B1 = [1,2,3,4,5,6,7]
dilimleme = B1[1:5:2]
print(dilimleme)

[2, 4]


In [ ]:
# Tüm dizideki diğer tüm öğeleri döndürün:
B1 = [1,2,3,4,5,6,7]
dilimleme = B1[::2]
print(dilimleme)

[1, 3, 5, 7]


In [31]:
# B2 dilimleme
# İkinci öğeden, öğeleri dizin 1'den dizin 4'e dilimleyin (dahil değildir):
B2 = np.array([[1,2,3,4],[5,6,7,8]])
dilimleme = B2[1, 1:4]
print(dilimleme)

[6 7 8]


In [34]:
B2 = np.array([[1,2,3,4],[5,6,7,8]])
dilimleme = B2[0:2, 2]
print(dilimleme)

[3 7]


In [37]:
B2 = np.array([[1,2,3,4],[5,6,7,8]])
dilimleme = B2[0:2, 1:2]
print(dilimleme)

[[2]
 [6]]
