27.01.2023

### Filtreleme Diziler

Varolan bir diziden bazı öğeleri çıkarma ve yeni bir dizi oluşturma bunlardan **filtreleme** denir.

NumPy'de, bir boole dizin listesi kullanarak bir diziye filtre uygularsınız.

Bir dizindeki değer o öğenin filtrelenmiş dizide yer almasıysa, bu dizindeki değer o öğeyse, filtre uygulanan diziden dışlanır.

In [1]:
import numpy as np

In [16]:
# 0 ve 2 dizinlerindeki öğelerden bir dizi oluşturun:
dizi = np.array([42,43,44,45])
x = [True,False,True,False]
yeniDizi = dizi[x]
print(x)
print(yeniDizi)

[True, False, True, False]
[42 44]


#### Filtre Dizisi Oluşturma

Yukarıdaki örnekte ve değerlerini sabit kodladık, ancak yaygın kullanım koşullara dayalı bir filtre dizisi oluşturmaktır.

In [10]:
# Yalnızca 42'den yüksek değerler döndürecek bir filtre dizisi oluşturun:
dizi = np.array([42,43,44,45])
x = []
for i in dizi:
    if i>42:
        x.append(True)
    else:
        x.append(False)
yeniDizi = dizi[x]
print(x)
print(yeniDizi)

[False, True, True, True]
[43 44 45]


In [23]:
# Orijinalden yalnızca çift öğeleri döndürecek bir filtre dizisi oluşturun dizi:
dizi = np.array([42,43,44,45])
x = []
for i in dizi:
    if i % 2 == 0:
        x.append(True)
    else:
        x.append(False)
yeniDizi = dizi[x]
print(x)
print(yeniDizi)


[True, False, True, False]
[42 44]


#### Doğrudan Diziden Filtre Oluşturma

In [14]:
# Yalnızca 42'den yüksek değerler döndürecek bir filtre dizisi oluşturun:
dizi = np.array([42,43,44,45])
filterDizi = dizi>42
yeniDizi = dizi[filterDizi]
print(filterDizi)
print(yeniDizi)

[False  True  True  True]
[43 44 45]


In [15]:
dizi = np.array([42,43,44,45])
filterDizi = dizi % 2 == 0 
yeniDizi = dizi[filterDizi]
print(filterDizi)
print(yeniDizi)

[ True False  True False]
[42 44]


In [60]:
dizi = np.array([[10,20,30],[40,50,60]])
dizi2 = dizi.reshape(-1)
filterDizi = dizi2 >20
print(filterDizi)
yeniDizi = dizi2[filterDizi]
print(yeniDizi)

[False False  True  True  True  True]
[30 40 50 60]
