26.01.2023

#### Dizi Birleştirme

SQL de sütunlar anahtarlarla birbirine birleştirilir. Numpyda ise eksenler birbirlerine birleştirilir.

In [11]:
import numpy as np

In [23]:
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
birlestirilmisDizi = np.concatenate((dizi1,dizi2))
print(birlestirilmisDizi)
print(birlestirilmisDizi.shape)

[1 2 3 4 5 6]
(6,)


In [22]:
# 2B dizileri birleştirme
dizi1 = np.array([[1,2,3],[4,5,6]])
dizi2 = np.array([[7,8,9],[10,11,12]])
birlestirilmisDizi = np.concatenate((dizi1,dizi2))
print(birlestirilmisDizi)
print(birlestirilmisDizi.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [47]:
# 2B dizileri birleştirme - eksen = 1
dizi1 = np.array([[1,2,3],[4,5,6]])
dizi2 = np.array([[7,8,9],[10,11,12]])
birlestirilmisDizi = np.concatenate((dizi1,dizi2), axis=1)
print(birlestirilmisDizi)
print(birlestirilmisDizi.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


#### Yığın İşlevlerini Kullanarak Dizileri Birleştirme

İstifleme işlemi birleştirme işlemi ile aynıdır. Farkı eksen boyunca birleştirme işlemi yapar.
Herhangi bir eksen vermezsek varsayılan 0 olarak alır.

In [49]:
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
istifliDizi = np.stack((dizi1,dizi2), axis=1)
print(istifliDizi)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
# hstack satırlar boyunca istifleme yapar.
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
istifliDizi = np.hstack((dizi1,dizi2))
print(istifliDizi)

[1 2 3 4 5 6]


In [39]:
# vstack sütunlar boyunca istifleme yapar.
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
istifliDizi = np.vstack((dizi1,dizi2))
print(istifliDizi)

[[1 2 3]
 [4 5 6]]


In [41]:
# dstack derinlikle aynı olan yükseklik boyunca istifleme yapar.
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
istifliDizi = np.dstack((dizi1,dizi2))
print(istifliDizi)

[[[1 4]
  [2 5]
  [3 6]]]
