26.01.2023

#### Numpy arama

Bir dizide belirlenen değeri arayabilir veya eşleşen dizinleri döndürebilir.

In [1]:
import numpy as np

In [3]:
dizi = np.array([1,2,3,4,4,5,6,4])
arama = np.where(dizi==4)
print(arama)

(array([3, 4, 7], dtype=int64),)


In [4]:
dizi = np.array([1,2,3,4,4,5,6,4])
arama = np.where(dizi%2==0)
print(arama)

(array([1, 3, 4, 6, 7], dtype=int64),)


In [5]:
dizi = np.array([1,2,3,4,4,5,6,4])
arama = np.where(dizi%2==1)
print(arama)

(array([0, 2, 5], dtype=int64),)


#### Numpy Sıralanmış Arama

In [19]:
import numpy as np

Dizide ikili arama yapan bir yöntem vardır, ve belirtilen değerin ekleneceği dizini döndürür. 


In [27]:
# searchsorted dizide ikili arama yaptıktan sonra ekleneceği dizini döndürür
dizi = np.array([1,2,3,4,5])
siraliDizi = np.searchsorted(dizi,3)
siraliDizi

2

In [28]:
dizi = np.array([1,2,3,4,5])
sagdansiraliDizi = np.searchsorted(dizi,3, side="right")
sagdansiraliDizi

3

In [29]:
dizi = np.array([1,3,5,7])
eklenmesiDizi = np.searchsorted(dizi,[2,4,6])
print(eklenmesiDizi)

[1 2 3]
