25.01.2023

### Copy and View 

#### Copy

In [1]:
# Kopyalama dizi verilerine sahiptir. Özgün görüntünün bir kopyasını oluştururur. 
# Kopyalamada yapılan değişiklikler kopyayı etkiler fakat özgün görüntüyü etkilemez.
import numpy as np
dizi = np.array([1,2,3,4,5])
copy = dizi.copy()
dizi[0] = 42
print(dizi)
print(copy)

[42  2  3  4  5]
[1 2 3 4 5]


#### View

In [2]:
# Görünüm dizi verilerine sahip değildir. Özgün görüntünün kendisidir.
# Görünümde yapılan değişiklikler hem görünümü etkiler hem de özgün diziyi etkiler.
dizi = np.array([1,2,3,4,5])
view = dizi.view()
dizi[1] = 6
print(dizi)
print(view)

[1 6 3 4 5]
[1 6 3 4 5]


In [33]:
dizi[0] = 3
print(dizi)
print(view)

[3 6 3 4 5]
[3 6 3 4 5]


#### Base

In [3]:
# Base metoduyla dizinin verilere sahip olup olmadığını kontrol ederiz.
# Eğer veriye sahipse None verir. Değilse diziyi döndürür.

In [4]:
dizi = np.array([1,2,3,4,5])
copy = dizi.copy()
view = dizi.view()

print(copy.base)
print(view.base)

None
[1 2 3 4 5]
