26.01.2023

#### Numpy Sıralama

Dizilerde sıralama yapar.

In [1]:
import numpy as np

In [4]:
dizi = np.array([1,4,2,3,5])
siraliDizi = np.sort(dizi)
print(siraliDizi)

[1 2 3 4 5]


In [5]:
meyveDizisi = np.array(["Elma","Armut","Muz","Kiraz"])
siraliMeyveDizisi = np.sort(meyveDizisi)
print(siraliMeyveDizisi)

['Armut' 'Elma' 'Kiraz' 'Muz']


In [6]:
boolDizisi = np.array([True,False,False,True,True])
siraliBoolDizisi = np.sort(boolDizisi)
print(siraliBoolDizisi)

[False False  True  True  True]


In [8]:
dizi2B = np.array([[1,5,3],[8,4,2]])
siraliDizi2B = np.sort(dizi2B)
print(siraliDizi2B)

[[1 3 5]
 [2 4 8]]
