26.01.2023

#### Reshape

In [6]:
# Dizi özniteliklerini yeniden boyutlandırma yapar. Shape
# Satır * Sütun
# Yeniden boyutlandırma yaparken dizinin eleman sayısına göre yapılır. Aksi takdirde hata verir.

In [7]:
import numpy as np

In [32]:
# 1B den 2B ye yeniden şekillendirme
dizi = np.array([1,2,3,4,5,6])
yeniDizi = dizi.reshape(2,3)
print(f"Eski dizi boyutu: {dizi.shape}","\n")
print(f"{yeniDizi}","\n")
print(f"Yeni dizi boyutu: {yeniDizi.shape}","\n")

Eski dizi boyutu: (6,) 

[[1 2 3]
 [4 5 6]] 

Yeni dizi boyutu: (2, 3) 



In [33]:
# 1B den 2B ye yeniden şekillendirme
dizi2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
yeniDizi2 = dizi2.reshape(4,3)
print(f"Eski dizi boyutu: {dizi2.shape}","\n")
print(f"{yeniDizi2}","\n")
print(f"Yeni dizi boyutu: {yeniDizi2.shape}","\n")

Eski dizi boyutu: (12,) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

Yeni dizi boyutu: (4, 3) 



In [34]:
# 1B den 3B ye yeniden şekillendirme
dizi3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
yeniDizi3 = dizi3.reshape(2,3,2)
print(f"Eski dizi boyutu: {dizi3.shape}","\n")
print(f"{yeniDizi3}","\n")
print(f"Yeni dizi boyutu: {yeniDizi3.shape}","\n")

Eski dizi boyutu: (12,) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 

Yeni dizi boyutu: (2, 3, 2) 



In [35]:
# 1B den 3B ye yeniden şekillendirme
dizi3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
yeniDizi3 = dizi3.reshape(3,2,2)
print(f"Eski dizi boyutu: {dizi3.shape}","\n")
print(f"{yeniDizi3}","\n")
print(f"Yeni dizi boyutu: {yeniDizi3.shape}","\n")

Eski dizi boyutu: (12,) 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 

Yeni dizi boyutu: (3, 2, 2) 



In [36]:
# 1B den 3B ye yeniden şekillendirme
dizi3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
yeniDizi3 = dizi3.reshape(4,3,1)
print(f"Eski dizi boyutu: {dizi3.shape}","\n")
print(f"{yeniDizi3}","\n")
print(f"Yeni dizi boyutu: {yeniDizi3.shape}","\n")

Eski dizi boyutu: (12,) 

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]] 

Yeni dizi boyutu: (4, 3, 1) 



#### Kopyalama ve Görünümü döndürür mü?

In [41]:
# Kopyalama mı yoksa Görünüm mü?
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
yeniDizi = dizi.reshape(4,3).base
print(yeniDizi)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Yukarıdaki örnek orijinal diziyi döndürür, bu nedenle bu bir görünümdür.

#### Dizi düzleştirme


In [51]:
# Çok boyutlu bir diziyi 1B ye dönüştürme: -1

In [49]:
# 2B diziyi 1B ye indirgeme
dizi2B = np.array([[1,2,3],[4,5,6]])
duzDizi = dizi2B.reshape(-1)
print(f"{dizi2B}")
print(f"Eski dizi boyutu: {dizi2B.shape}","\n")
print(f"{duzDizi}",)
print(f"Yeni dizi boyutu: {duzDizi.shape}","\n")

[[1 2 3]
 [4 5 6]]
Eski dizi boyutu: (2, 3) 

[1 2 3 4 5 6]
Yeni dizi boyutu: (6,) 



#### Bilinmeyen Boyut

Tek bir "bilinmeyen" boyuta sahip olmanıza izin verilir.

Bu, aşağıdakilerden biri için tam bir sayı belirtmeniz gerekmediği anlamına gelir. Yeniden şekillendirme yönteminde boyutlar.

In [57]:
dizi = np.array([1,2,3,4,5,6,7,8])
yeniDizi = dizi.reshape(2,2,-1)
print(yeniDizi)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
