26.01.2023

In [1]:
import numpy as np

In [11]:
# skaler dizi yineleme
dizi1B = np.array([1,2,3,4,5,6])
for i in dizi1B:
    print(i)

1
2
3
4
5
6


In [12]:
# 2B dizi yineleme
dizi2B = np.array([[1,2,3],[4,5,6]])
for i in dizi2B:
    print(i)

[1 2 3]
[4 5 6]


In [15]:
# 3B dizi yineleme
dizi3B = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in dizi3B:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [16]:
# 2B diziyi skaler üzerinde yineleme
dizi2B = np.array([[5,10,15],[20,25,30]])
for i in dizi2B:
    for x in i:
        print(x)

5
10
15
20
25
30


In [18]:
# 3B diziyi skalere dönüştürerek yineleme
dizi3B = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in dizi3B:
    for x in i:
        for y in x:
            print(y)

1
2
3
4
5
6
7
8
9
10
11
12
